import {HButton} from "hbutton.slint";
import {Status,NewProjectConfig} from "status.slint";
import {HorizontalBox, LineEdit, TextEdit} from "std-widgets.slint";
import { Chooser } from "chooser.slint";

export component StartMenu {
    //--title--
    Text {
        text: " Project\nManager";
        y: 50px;
        font-size: 40px;
    }

    // //--openproject--
        // HButton {  
        //     width: 100px;
        //     x:-25px;
        //     height: 35px;
        //     y:100px;   
        //     text: "打开";
        //     clicked => {
        //         Status.nowtab = 3;
        //         Status.lasttab = 1;
        //     }
        // }
        //--newproject--
        HButton {
        width: 100px;
        height: 35px;
        x: -25px;
        y: 100px;
        text: "新建";
        clicked => {
            Status.nowtab = 2;
            Status.lasttab = 1;
        
        }
    }

    //--listproject--
        list := HButton {
        width: 100px;
        height: 35px;
        x: -25px;
        y: 120px;
        text: "列表";
        clicked => {
            Status.nowtab = 4;
            Status.lasttab = 1;
        
        }
    }

    //--settings--
    HButton {
        width: 100px;
        height: 35px;
        x: -25px;
        y: 140px;
        text: "设置";
        clicked => {
            Status.nowtab = 5;
            Status.lasttab = 1;
        }
    }

    //--about--
    HButton {
        width: 100px;
        height: 35px;
        x: -25px;
        y: 160px;
        text: "关于";
        clicked => {
            Status.nowtab = 7;
            Status.lasttab = 1;
        }
    }
}
