export global Status {
    /*
    1:StartMenu
    2:NewMenu
    3:OpenMenu
    4:ListMenu
    5:SettingsMenu
    6:ProjectPanel
    7:AboutPanel
    */
    in-out property <int> nowtab : 1;
    in-out property <int> lasttab : 1;
    out property <string> version : "dev-497319c";
}

export global NewProjectConfig {
    in-out property <string> project-name;
    in-out property <string> describe;
    in-out property <string> path;
    in-out property <string> lang;
}
